spring:
  application:
    name: k8s
  profiles:
    active: production

server:
  port: 8081

logging:
  file:
    path: '/var/log/spring'
  level:
    root: 'info'
    org.springframework.web.servlet.DispatcherServlet: 'trace'
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: 'off'

